services:
  snort3:
    # image: issgupat/snort-docker-sand5g:latest
    build:
      context: ./src
      dockerfile: Dockerfile
    hostname: snort3
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - /path/to/custom:/home/snorty/custom
      - alerts_data:/home/snorty/alerts
      - /etc/localtime:/etc/localtime:ro # Bind mount to sync time
    environment:
      - SNORT_ALERTS=/home/snorty/alerts
      # - RULES_FILE=/home/snorty/custom/local.rules
      # - SNORT_CONF_FILE=/home/snorty/custom/custom_snort.lua
      - INTERFACE=<INTERFACE>
      - VERBOSE=<level>
      - TZ=Europe/Athens

    privileged: true
    stdin_open: true
    tty: true
    restart: unless-stopped

volumes:
  alerts_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /path/to/alerts
