services:
  snort3:
    image: issgupat/snort-docker-sand5g:latest
    hostname: snort3
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - custom_data:/home/snorty/custom
      - alerts_data:/home/snorty/alerts
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Athens
      - RULES_FILE=/home/snorty/custom/<FILE.RULES>
      - INTERFACE=<INTERFACE>
      - VERBOSE=<0|1>
      - SNORT_ALERT_MODE=<ALERT_MODE>
      - SNORT_DAQ_MODE=<nfq|pcap>
      - INTERFACE=<INTERFACE>
    privileged: true
    stdin_open: true
    tty: true
    restart: unless-stopped

volumes:
  alerts_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /path/to/alerts

  custom_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /path/to/custom
