FROM snort-from-scratch:latest

USER root
RUN apt-get install -y iptables

COPY volumes/scripts /home/snorty/scripts

RUN chmod +x /home/snorty/scripts/entrypoint.sh \
    && chmod +x /home/snorty/scripts/run_snort.sh \
    && chmod +x /home/snorty/scripts/run_snort_notify.sh

USER snorty
WORKDIR /home/snorty

ENTRYPOINT ["/home/snorty/scripts/entrypoint.sh"]
